### ISSUE TITLE
Zope does no longer start with Products.TemporaryFolder = 6.0

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/Products.TemporaryFolder#13] opened 2020-09-11 16:22 UTC
After upgrading the package...

```
❯ bin/bliss
2020-09-11 17:43:00,344 INFO    [ZEO.ClientStorage:209][MainThread] zeostorage ClientStorage (pid=907) created RW/normal for storage: 'main'
2020-09-11 17:43:00,345 INFO    [ZEO.cache:208][MainThread] created temporary cache file 10
2020-09-11 17:43:00,352 INFO    [ZEO.asyncio.base:51][zeostorage zeo client networking thread] Connected Protocol(('localhost', 9000), 'main', False)
2020-09-11 17:43:00,353 INFO    [ZEO.ClientStorage:366][zeostorage zeo client networking thread] zeostorage Connected to storage: ('localhost', 9000)
2020-09-11 17:43:00,355 WARNING [TemporaryStorage:93][MainThread] DEPRECATED: Usage of the package tempstorage is deprecated, as it is known to randomly lose data.
Especially on Zope 4. For details see https://github.com/zopefoundation/tempstorage/issues/8
and https://github.com/zopefoundation/tempstorage

2020-09-11 17:43:00,356 INFO    [ZEO.ClientStorage:209][MainThread] bliss ClientStorage (pid=907) created RW/normal for storage: 'bliss'
2020-09-11 17:43:00,356 INFO    [ZEO.cache:199][MainThread] created persistent cache file '/home/jugmac00/Projects/bliss_deployment/work/zope/parts/instance/var/zeoclient_bliss-bliss.zec'
2020-09-11 17:43:00,362 INFO    [ZEO.asyncio.base:51][bliss zeo client networking thread] Connected Protocol(('localhost', 9000), 'bliss', False)
2020-09-11 17:43:00,363 INFO    [ZEO.ClientStorage:366][bliss zeo client networking thread] bliss Connected to storage: ('localhost', 9000)
2020-09-11 17:43:00,498 INFO    [chameleon.config:38][MainThread] directory cache: /home/jugmac00/Projects/bliss_deployment/work/zope/var/cache.
Traceback (most recent call last):
  File "/home/jugmac00/Projects/bliss_deployment/work/zope/parts/instance/bin/interpreter", line 183, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "/home/jugmac00/Projects/bliss_deployment/work/_/home/jugmac00/.batou-shared-eggs/Zope-4.5.1-py3.7.egg/Zope2/Startup/serve.py", line 255, in <module>
    sys.exit(main() or 0)
  File "/home/jugmac00/Projects/bliss_deployment/work/_/home/jugmac00/.batou-shared-eggs/Zope-4.5.1-py3.7.egg/Zope2/Startup/serve.py", line 251, in main
    return command.run()
  File "/home/jugmac00/Projects/bliss_deployment/work/_/home/jugmac00/.batou-shared-eggs/Zope-4.5.1-py3.7.egg/Zope2/Startup/serve.py", line 190, in run
    global_conf=vars)
  File "/home/jugmac00/Projects/bliss_deployment/work/_/home/jugmac00/.batou-shared-eggs/Zope-4.5.1-py3.7.egg/Zope2/Startup/serve.py", line 220, in loadapp
    return loadapp(app_spec, name=name, relative_to=relative_to, **kw)
  File "/home/jugmac00/Projects/bliss_deployment/work/_/home/jugmac00/.batou-shared-eggs/PasteDeploy-2.1.0-py3.7.egg/paste/deploy/loadwsgi.py", line 253, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/jugmac00/Projects/bliss_deployment/work/_/home/jugmac00/.batou-shared-eggs/PasteDeploy-2.1.0-py3.7.egg/paste/deploy/loadwsgi.py", line 278, in loadobj
    return context.create()
  File "/home/jugmac00/Projects/bliss_deployment/work/_/home/jugmac00/.batou-shared-eggs/PasteDeploy-2.1.0-py3.7.egg/paste/deploy/loadwsgi.py", line 715, in create
    return self.object_type.invoke(self)
  File "/home/jugmac00/Projects/bliss_deployment/work/_/home/jugmac00/.batou-shared-eggs/PasteDeploy-2.1.0-py3.7.egg/paste/deploy/loadwsgi.py", line 209, in invoke
    app = context.app_context.create()
  File "/home/jugmac00/Projects/bliss_deployment/work/_/home/jugmac00/.batou-shared-eggs/PasteDeploy-2.1.0-py3.7.egg/paste/deploy/loadwsgi.py", line 715, in create
    return self.object_type.invoke(self)
  File "/home/jugmac00/Projects/bliss_deployment/work/_/home/jugmac00/.batou-shared-eggs/PasteDeploy-2.1.0-py3.7.egg/paste/deploy/loadwsgi.py", line 152, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/home/jugmac00/Projects/bliss_deployment/work/_/home/jugmac00/.batou-shared-eggs/PasteDeploy-2.1.0-py3.7.egg/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/home/jugmac00/Projects/bliss_deployment/work/_/home/jugmac00/.batou-shared-eggs/Zope-4.5.1-py3.7.egg/Zope2/Startup/run.py", line 71, in make_wsgi_app
    starter.prepare()
  File "/home/jugmac00/Projects/bliss_deployment/work/_/home/jugmac00/.batou-shared-eggs/Zope-4.5.1-py3.7.egg/Zope2/Startup/starter.py", line 41, in prepare
    self.startZope()
  File "/home/jugmac00/Projects/bliss_deployment/work/_/home/jugmac00/.batou-shared-eggs/Zope-4.5.1-py3.7.egg/Zope2/Startup/starter.py", line 99, in startZope
    Zope2.startup_wsgi()
  File "/home/jugmac00/Projects/bliss_deployment/work/_/home/jugmac00/.batou-shared-eggs/Zope-4.5.1-py3.7.egg/Zope2/__init__.py", line 50, in startup_wsgi
    _startup()
  File "/home/jugmac00/Projects/bliss_deployment/work/_/home/jugmac00/.batou-shared-eggs/Zope-4.5.1-py3.7.egg/Zope2/App/startup.py", line 154, in startup
    application._p_jar.close()
  File "/home/jugmac00/Projects/bliss_deployment/work/_/home/jugmac00/.batou-shared-eggs/ZODB-5.6.0-py3.7.egg/ZODB/Connection.py", line 320, in close
    connection.close(False)
  File "/home/jugmac00/Projects/bliss_deployment/work/_/home/jugmac00/.batou-shared-eggs/ZODB-5.6.0-py3.7.egg/ZODB/Connection.py", line 283, in close
    raise ConnectionStateError("Cannot close a connection joined to "
ZODB.POSException.ConnectionStateError: Cannot close a connection joined to a transaction
```
Looks like my Zope app is "using" a temp folder - within the temp folder, there is a "Transient Object Container" with the name `session_data`.

The date time of the `session_data` is "2020-09-10 23:23" - at this time I certainly did not work on my app - I am still unsure where `session_data` comes from and whether I need the temp folder at all.

In my local dev environment I removed the following snippet from my zope.conf and so Zope starts again - at least:
```
<zodb_db temporary>
    # Temporary storage database (for sessions)
    <temporarystorage>
      name temporary storage for sessioning
    </temporarystorage>
    mount-point /temp_folder
    container-class Products.TemporaryFolder.TemporaryContainer
</zodb_db>
```

When starting Zope, there was some error message (`ZConfig.ConfigurationError: No database configured for mount point at /temp_folder`) - when I go to the ZMI and delete the temp folder, there is no more error message at start up - also the app seems to work flawlessly. Tests also pass.

Can anybody explain to me why my Zope did not start at all? It looks like the snippet above is just the same from the README here - so it is supposed to work, right?

Can anybody tell me where this "session_data" transient folder was coming from?

So it looks like, I had the temp folder in my ZODB, but I was not using it - except for the updated time stamp of the session_data folder - which is a little bit worrying. If nothing would use the temp folder and session_data, why is the time stamp from yesterday night?

This all said - the upgrade experience from TemporaryFolder 5.3 to 6 was not smooth for me. Is my case so super special or would it make sense to update the README? (e.g. delete an existing temp folder before updating to 6.0.. ?)

**Comment by dataflake** [comment] 2020-09-11 17:07
I have tried to reproduce the problem but can only do it partially. I have a buildout configuration that uses `plone.recipe.zope2instance` to create a Zope instance with Zope 4.5.1 and explicitly pull in `Products.TemporaryStorage` with `eggs`.

1) I set the flag `zodb-temporary-storage = on` for the buildout instance configuration and set the required version for `Products.TemporaryFolder` to 5.3. That way I get the `zodb_db temporary` configuration into the instance, exactly like the one you pasted above, and create a pre-upgrade state.

At this point the instance starts fine. `/temp_folder` is created (this is done by the `zodb_db temporary` Zope configuration) and the old `Products.TemporaryFolder` code will magically create session-related objects like the  `session_data` item inside it.

2) I stop the instance and set the required version for `Products.TemporaryFolder` to 6 and rebuild.

When I look at the ZMI I still have `/temp_folder` due to the still-existing `zodb_db temporary` Zope configuration. However, since the new version of `Products.TemporaryFolder` no longer magically creates the `session_data` object `/temp_folder` is empty. When I click into the Session Data Manager object at `/session_data_manager` I get a log entry that `/temp_folder/session_data` is gone - that's expected. The "Session data container path" attribute must be changed to a valid session data container path.

3) I set `zodb-temporary-storage = off` in the buildout configuration to get rid of the temporary ZODB entry and rebuild.

Now the startup complaint about `tempstorage` is gone. But when I click into the ZMI I see the tracebacks `no database configured for mount point at /temp_folder`. But Zope is up and running and I can use it just fine.

To get rid of the tracebacks I rebuild with `zodb-temporary-storage = on`, restart and explicitly delete `/temp_folder` in the ZMI. Then I stop the instance, set `zodb-temporary-storage = off`, rebuild and restart. Now the tracebacks are gone.

I have added a note at the bottom of `README.md` to advise the manual deletion of `/temp_folder`. Other than that I was unable to reproduce the other issues and cannot answer the other questions.

**Comment by d-maurer** [comment] 2020-09-11 18:06
Jürgen Gmach wrote at 2020-9-11 09:23 -0700:
>After upgrading the package...
> ...
>  File "/home/jugmac00/Projects/bliss_deployment/work/_/home/jugmac00/.batou-shared-eggs/Zope-4.5.1-py3.7.egg/Zope2/App/startup.py", line 154, in startup
>    application._p_jar.close()
> ...
>ZODB.POSException.ConnectionStateError: Cannot close a connection joined to a transaction

This looks as if the initialization in line 155 has
forgotten a `transaction.commit` (or `abort`).

> ...
>Looks like my Zope app is "using" a temp folder - within the temp folder, there is a "Transient Object Container" with the name `session_data`.

For me, it does not look like this.
Instead, I think that the initialization modifies a persistent object
and nevertheless transaction control is forgotten.
I would use debugging to determine which objects have been
modified in `application._p_jar`. This should give hints
which package is responsible for the forgotten transaction control.

> ...
>Can anybody explain to me why my Zope did not start at all?

See above (no complete explanation, though).

> ...
>Can anybody tell me where this "session_data" transient folder was coming from?

I know that it is part of Zope's session machinery.

It used to be automatically created on startup (when it was not yet present --
because with a `tempstortage` is was gone after each restart)
as part of the "application" initialization. You
should find the code in `OFS.Application.initialize` (though it
may be in nested calls).

>So it looks like, I had the temp folder in my ZODB

Likely, you had it as a so called "mount point".

> but I was not using it - except for the updated time stamp of the session_data folder - which is a little bit worrying.

As explained above, the `session_data` needs to be automatically created
on startup (at least when it is `tempstorage` hosted - because then
it is maintained in RAM and disappears on shutdown).

>If nothing would use the temp folder and session_data, why is the time stamp from yesterday night?

Have you started at that time? Then is was created on startup.

>This all said - the upgrade experience from TemporaryFolder 5.3 to 6 was not smooth for me. Is my case so super special or would it make sense to update the README? (e.g. delete an existing temp folder before updating to 6.0.. ?)

Apparently, you have an old configuration with support for Zope's
session machinery (--> a mount point at `temp_folder`).
For a different configuration nothing related to `temp_folder`,
`session_data` etc. would happen and `Products.TemporaryFolder` should
not need to be installed at all.

If you need sessions, you must ensure that the corresponding
objects are available, at least `browser_id_manager`
and `session_data_manager`. Their configuration may require additional
objects.


Thus: first decide whether or not your application wants to use
Zope's sessions.

If no, remove configuration related to Zope's session machinery
(and maybe also (old) session related objects in the ZODB).
You may also not install the corresponding code.

If yes, ensure your configuration supports Zope's session machinery;
install the related code packages. The remaining parts used to be
automatic (but this might have changed in recent versions).

**Comment by jugmac00** [comment] 2020-09-14 13:09
Thank you very much for having a look into this, both of you!

The time stamp of the session data results due to a reboot of the virtual machine due to a Kernel update.

Thanks for the hint about `plone.recipe.zope2instance`s `zodb-temporary-storage`!

I was not aware of this option. I had a look at the source code, and this one defaults to `on`:

```
zodb_tmp_storage = options.get('zodb-temporary-storage', 'on')
```

In my case, it was not set, so it was turned on by default.

So now I can set the option to off, delete the temp folder, and then deploy my app without `Products.TemporaryFolder`.


By best effort, I found some session related code, but that one is hand crafted and does not use any Zope machinery as far as I can tell (cookies + mysql entries).


What I did find out however, my code seems to be implicitly dependent on `Products.ZODBMountPoint`.

I noticed that when I removed `Products.TemporaryStorage`, and I received the following traceback:

```
STDERR
     Traceback (most recent call last):
       File "/home/jugmac00/Projects/bliss_deployment/work/_/home/jugmac00/.batou-shared-eggs/Zope-4.5.1-py3.7.egg/OFS/Traversable.py", line 297, in unrestrictedTraverse
         next = obj[name]
     TypeError: 'MountedObject' object is not subscriptable
     
     During handling of the above exception, another exception occurred:
     
     Traceback (most recent call last):
       File "/home/jugmac00/Projects/bliss_deployment/work/source/bliss.git/src/Products/Relateable/MetaManager.py", line 911, in recreateIndexes
         container = self.unrestrictedTraverse(base_path)
       File "/home/jugmac00/Projects/bliss_deployment/work/_/home/jugmac00/.batou-shared-eggs/Zope-4.5.1-py3.7.egg/OFS/Traversable.py", line 343, in unrestrictedTraverse
         raise e
       File "/home/jugmac00/Projects/bliss_deployment/work/_/home/jugmac00/.batou-shared-eggs/Zope-4.5.1-py3.7.egg/OFS/Traversable.py", line 309, in unrestrictedTraverse
         raise NotFound(name)
     zExceptions.NotFound: Products
     
     During handling of the above exception, another exception occurred:
     
     Traceback (most recent call last):
       File "/home/jugmac00/Projects/bliss_deployment/work/zope/parts/runner/bin/interpreter", line 168, in <module>
         exec(_val)
       File "<string>", line 1, in <module>
       File "/home/jugmac00/Projects/bliss_deployment/work/zope/bin/load_uml.py", line 18, in <module>
         result = app['IDE'].zuml_parseAndCheckinModel(config, app.REQUEST)
       File "/home/jugmac00/Projects/bliss_deployment/work/source/bliss.git/src/Products/IDE/IDEContainer.py", line 103, in zuml_parseAndCheckinModel
         mm.recreateIndexes(ret, configDict['managerPath'])
       File "/home/jugmac00/Projects/bliss_deployment/work/source/bliss.git/src/Products/Relateable/MetaManager.py", line 925, in recreateIndexes
         dataContainer._setObject(folder_name, f)
     AttributeError: 'MountedObject' object has no attribute '_setObject'
```

The debugger revealed the following problem:
```
-> dataContainer._setObject(folder_name, f)
(Pdb++) dataContainer
<persistent broken Products.ZODBMountPoint.MountedObject.MountedObject instance b'\x00\x00\x00\x00\x00\x08\xb9\xf7'>
```

Interesingly, or let's say, completely confusing for me, the very same code executed with `Products.TemporaryFolder=5.3` (incl. `Products.ZODBMountPoint`), gave me this result:

```
(Pdb++) data_path
'/bliss/data'
(Pdb++) self.unrestrictedTraverse(data_path)
<Folder at /bliss/data>
(Pdb++) self.unrestrictedTraverse(data_path).__class__
<class 'OFS.Folder.Folder'>
(Pdb++) 
```

So, the very same folder is one time a `OFS.Folder.Folder` and the other time a `MountedObject` :-O

The "fix" was to add `Products.ZODBMountPoint` to the eggs section of my buildout.cfg.

I grepped my source, and I could neither find anything which imports something from `ZODBMountPoint` nor which makes use of `manage_addMounts`.


In general, this issue seems to be resolved for me.

I'd very happy if somebody could explain me where this seemingly implicit dependency to `ZODBMountPoint` could derive from.

Also, as I understood, the usage of `Products.TemporaryFolder` is deprecated.

Is the usage of `ZODBMountPoint` safe for the forseeable future? Or is this something I should focus on, find out how this gets used, and try to find a replacement?

Thanks again!

**Comment by dataflake** [comment] 2020-09-14 13:17
`Products.ZODBMountPoint` is OK to use. The whole reason for the exercise was to split it out from `Products.TemporaryFolder` because it is useful by itself and without the deprecated TemporaryFolder stuff.

You're unlikely to find calls to `manage_addMounts` - mount points are added automatically if you have Zope configuration sections `zodb_db`, like the sample you quote at the top for `/temp_folder`. So search through your Zope configurations first.

**Comment by jugmac00** [comment] 2020-09-14 13:23
Thanks! That's it!

So this snippet...

```
zope-conf-additional =
       <zodb_db bliss_data>
           <zeoclient>
               name bliss
               server {{component.zeo.address.connect}}
               storage bliss
               var ${buildout:directory}/parts/${:_buildout_section_name_}/var
               cache-size 2500MB
               ${:bliss_zeo_client}
               drop-cache-rather-verify true
               shared-blob-dir off
           </zeoclient>
           mount-point /bliss/data
           cache-size 40000
           cache-size-bytes 500000000
       </zodb_db>
```

... requires `Products.ZODBMountPoint`.

Adding a comment right now in order to avoid future confusion :-D

Thanks a lot!

**Comment by dataflake** [comment] 2020-09-14 13:28
This also tells you that if you don't specify a value for `container-class` in your `zodb_db` section you get a standard `OFS.Folder.Folder`.

Feel free to close the issue.

**Closed as completed** 2020-09-14 14:07 UTC
